#!/usr/bin/env ruby -wKU
require File.join(File.dirname(__FILE__), %w(.. lib version))

strategery_file = File.join(File.dirname(__FILE__), %w(.. lib strategery))
console_file = File.join(File.dirname(__FILE__), %w(.. lib console_app))

irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'

require 'optparse'
options = { :sandbox => false, :irb => irb }
OptionParser.new do |opt|
  opt.banner = "Usage: console [environment] [options]"
  opt.on("--irb=[#{irb}]", 'Invoke a different irb.') { |v| options[:irb] = v }
  opt.parse!(ARGV)
end

libs =  " -r irb/completion -r #{strategery_file} -r #{console_file}"

ENV['STRATEGERY_ENV'] = case ARGV.first
  when "p": "production"
  when "d": "development"
  when "t": "test"
  else
    ARGV.first || ENV['STRATEGERY_ENV'] || 'development'
end

if options[:sandbox]
  puts "I'll have to think about how the whole sandbox concept should work for this project"
else
  puts "Loading #{ENV['strategery_ENV']} environment (Strategery #{SVM::VERSION::STRING})"
end
exec "#{options[:irb]} #{libs} --simple-prompt"
